services:
  - type: web
    name: Tripod_SignIn_App
    runtime: node
    buildCommand: cd client && npm install && npm run build && cd ../server && npm install
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: VITE_APP_URL
        value: https://tripod-signin-app.onrender.com
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: EMAIL_SERVICE
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_FROM
        sync: false
