#!/bin/bash
echo "Verifying deployment..."
echo ""
echo "1. Checking server index.html has new asset hashes..."
grep -o "index-BxXs0ckM.js" ../server/public/index.html && echo "✓ Server has updated build"
echo ""
echo "2. Checking PublicLanding component exists..."
grep -q "PublicLanding" ../client/src/App.jsx && echo "✓ PublicLanding route added"
echo ""
echo "3. Public features available:"
echo "   - Landing page: https://tripod-signin-app.onrender.com/"
echo "   - Admin signup: https://tripod-signin-app.onrender.com/admin/register"
echo "   - Visitor check-in: https://tripod-signin-app.onrender.com/checkin/TRIPOD"
echo ""
echo "Deployed successfully!"
