import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, FlatList, Modal, RefreshControl, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ArrowLeft, CalendarDays, Download, FileText, Package, Plus, RefreshCw, Search, X } from 'lucide-react-native';
import * as FileSystem from 'expo-file-system';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { useAuth } from '../context/AuthContext';
import api from '../services/api';

const formatDate = (value) => value ? new Date(value).toLocaleString('en-GB', { dateStyle: 'medium', timeStyle: 'short' }) : '—';
const esc = (v) => String(v ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

export default function DeliveriesScreen({ navigation, route }) {
  const { user } = useAuth();
  const siteId = route?.params?.siteId || user?.project_id || user?.site_id;
  const [deliveries, setDeliveries] = useState([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [dateFrom, setDateFrom] = useState('');
  const [dateTo, setDateTo] = useState('');
  const [selected, setSelected] = useState(null);
  const [exporting, setExporting] = useState(false);
  const load = useCallback(async () => {
    if (!siteId) { setLoading(false); return; }
    try { const response = await api.get('/deliveries', { params: { site_id: siteId, search: search || undefined, date_from: dateFrom || undefined, date_to: dateTo || undefined } }); setDeliveries(response.data || []); }
    catch (err) { Alert.alert('Could not load deliveries', err.response?.data?.error || 'Please try again.'); }
    finally { setLoading(false); }
  }, [siteId, search, dateFrom, dateTo]);
  useEffect(() => { const timer = setTimeout(load, 250); return () => clearTimeout(timer); }, [load]);
  useEffect(() => { if (route?.params?.deliveryId && deliveries.length) setSelected(deliveries.find((d) => String(d._id || d.id) === String(route.params.deliveryId)) || null); }, [deliveries, route?.params?.deliveryId]);
  const list = useMemo(() => deliveries, [deliveries]);
  const exportReport = async (format, reportItems = list, reportTitle = 'Delivery Report') => {
    if (!reportItems.length) return Alert.alert('Nothing to export', 'No deliveries match the current search and date filters.');
    setExporting(true);
    try {
      const rows = reportItems.map((d) => `<tr><td>${esc(d.itemName || d.recipient)}</td><td>${esc(d.recipient)}</td><td>${esc(d.company)}</td><td>${esc(d.carRegistration)}</td><td>${esc(formatDate(d.receivedAt || d.createdAt))}</td><td>${d.collected ? 'Collected' : 'Awaiting collection'}</td></tr>`).join('');
      const html = `<html><body style="font-family:Arial;padding:24px;color:#111827"><h2>${esc(reportTitle)}</h2><p>Period: ${esc(dateFrom || 'All dates')} to ${esc(dateTo || 'Today')}</p><table style="width:100%;border-collapse:collapse" border="1" cellpadding="7"><tr><th>Item</th><th>Recipient</th><th>Company</th><th>Vehicle</th><th>Received</th><th>Status</th></tr>${rows}</table></body></html>`;
      if (format === 'pdf') { const { uri } = await Print.printToFileAsync({ html }); await Sharing.shareAsync(uri, { mimeType:'application/pdf', dialogTitle:'Delivery report (PDF)' }); }
      else { const uri = `${FileSystem.cacheDirectory}delivery-report.xls`; await FileSystem.writeAsStringAsync(uri, html, { encoding: FileSystem.EncodingType.UTF8 }); await Sharing.shareAsync(uri, { mimeType:'application/vnd.ms-excel', dialogTitle:'Delivery report (Excel)' }); }
    } catch (err) { Alert.alert('Export failed', err.message || 'Could not create the report.'); }
    finally { setExporting(false); }
  };
  const detail = (d) => <Modal visible={!!d} transparent animationType="slide" onRequestClose={() => setSelected(null)}><View style={s.overlay}><View style={s.sheet}><View style={s.detailHeader}><Text style={s.detailTitle}>Delivery Details</Text><TouchableOpacity onPress={() => setSelected(null)}><X size={22} color="#64748b" /></TouchableOpacity></View><View style={s.packageIcon}><Package size={30} color="#c2410c" /></View><Text style={s.itemTitle}>{d?.itemName || d?.recipient || 'Delivery'}</Text><Text style={s.status}>{d?.collected ? 'Collected' : 'Awaiting Collection'}</Text>{[['Recipient',d?.recipient],['Company',d?.company],['Description',d?.description || d?.notes],['Car Registration',d?.carRegistration],['Received',formatDate(d?.receivedAt || d?.createdAt)],['Collected',d?.collected ? formatDate(d?.collectedAt) : 'Not collected']].map(([label, value]) => <View key={label} style={s.detailRow}><Text style={s.detailLabel}>{label}</Text><Text style={s.detailValue}>{value || '—'}</Text></View>)}<TouchableOpacity style={s.detailExport} onPress={() => Alert.alert('Download this delivery', 'Choose a format', [{text:'PDF',onPress:()=>exportReport('pdf',[d],'Delivery Details')},{text:'Excel (.xls)',onPress:()=>exportReport('excel',[d],'Delivery Details')},{text:'Cancel',style:'cancel'}])}><Download size={18} color="#fff" /><Text style={s.buttonText}>Download Details</Text></TouchableOpacity></View></View></Modal>;
  return <SafeAreaView style={s.page} edges={['top']}><View style={s.header}><TouchableOpacity onPress={() => navigation.goBack()}><ArrowLeft size={23} color="#111827" /></TouchableOpacity><Package size={21} color="#2b4594" /><Text style={s.title}>Deliveries</Text><TouchableOpacity onPress={load}><RefreshCw size={19} color="#64748b" /></TouchableOpacity></View><View style={s.filters}><View style={s.search}><Search size={16} color="#64748b" /><TextInput value={search} onChangeText={setSearch} placeholder="Search item, recipient or company" style={s.searchInput} /></View><View style={s.dateRow}><View style={s.dateInput}><CalendarDays size={15} color="#2b4594" /><TextInput value={dateFrom} onChangeText={setDateFrom} placeholder="From YYYY-MM-DD" style={s.dateText} /></View><View style={s.dateInput}><CalendarDays size={15} color="#2b4594" /><TextInput value={dateTo} onChangeText={setDateTo} placeholder="To YYYY-MM-DD" style={s.dateText} /></View></View><TouchableOpacity disabled={exporting} onPress={() => Alert.alert('Download filtered report', 'Choose a format', [{ text:'PDF',onPress:()=>exportReport('pdf') },{ text:'Excel (.xls)',onPress:()=>exportReport('excel') },{ text:'Cancel',style:'cancel' }])} style={s.reportBtn}>{exporting ? <ActivityIndicator color="#2b4594" /> : <><Download size={17} color="#2b4594" /><Text style={s.reportText}>Download Filtered Report</Text></>}</TouchableOpacity></View>{loading ? <View style={s.center}><ActivityIndicator size="large" color="#2b4594" /></View> : <FlatList data={list} keyExtractor={(item) => String(item._id || item.id)} refreshControl={<RefreshControl refreshing={false} onRefresh={load} />} contentContainerStyle={list.length ? s.list : s.empty} ListEmptyComponent={<><Package size={42} color="#cbd5e1" /><Text style={s.emptyTitle}>No deliveries found</Text><Text style={s.emptyCopy}>Change the filters or add a delivery.</Text></>} renderItem={({ item }) => <TouchableOpacity style={s.card} onPress={() => setSelected(item)} activeOpacity={0.75}><View style={s.icon}><Package size={20} color="#c2410c" /></View><View style={s.meta}><Text style={s.name}>{item.itemName || item.recipient || 'Delivery'}</Text><Text style={s.sub}>For {item.recipient || 'site reception'}{item.company ? ` · ${item.company}` : ''}</Text><Text style={s.date}>{formatDate(item.receivedAt || item.createdAt)}</Text></View><FileText size={18} color="#64748b" /></TouchableOpacity>} />}{detail(selected)}<TouchableOpacity style={s.add} onPress={() => navigation.navigate('DeliveryForm', { siteId })}><Plus size={20} color="#fff" /><Text style={s.addText}>Add Delivery</Text></TouchableOpacity></SafeAreaView>;
}
const s = StyleSheet.create({page:{flex:1,backgroundColor:'#f8fafc'},header:{flexDirection:'row',alignItems:'center',gap:12,padding:18,backgroundColor:'#fff',borderBottomWidth:1,borderColor:'#e5e7eb'},title:{flex:1,fontSize:19,fontWeight:'800',color:'#111827'},filters:{padding:12,backgroundColor:'#fff',borderBottomWidth:1,borderColor:'#e5e7eb'},search:{flexDirection:'row',alignItems:'center',gap:8,borderWidth:1,borderColor:'#cbd5e1',borderRadius:10,paddingHorizontal:10,height:43},searchInput:{flex:1,fontSize:14,color:'#111827'},dateRow:{flexDirection:'row',gap:8,marginTop:8},dateInput:{flex:1,flexDirection:'row',alignItems:'center',gap:5,borderWidth:1,borderColor:'#cbd5e1',borderRadius:10,paddingHorizontal:8,height:40},dateText:{flex:1,fontSize:12,color:'#111827'},reportBtn:{marginTop:9,flexDirection:'row',justifyContent:'center',alignItems:'center',gap:7,paddingVertical:10,borderRadius:10,backgroundColor:'#eef2ff'},reportText:{fontWeight:'700',fontSize:13,color:'#2b4594'},center:{flex:1,alignItems:'center',justifyContent:'center'},list:{padding:16,paddingBottom:100},empty:{flexGrow:1,alignItems:'center',justifyContent:'center',padding:28},emptyTitle:{marginTop:14,fontSize:17,fontWeight:'700',color:'#334155'},emptyCopy:{marginTop:6,fontSize:14,color:'#64748b',textAlign:'center'},card:{flexDirection:'row',alignItems:'center',gap:12,backgroundColor:'#fff',borderRadius:14,padding:14,marginBottom:10,borderWidth:1,borderColor:'#e5e7eb'},icon:{width:42,height:42,borderRadius:12,backgroundColor:'#fff7ed',alignItems:'center',justifyContent:'center'},meta:{flex:1},name:{fontSize:15,fontWeight:'700',color:'#111827'},sub:{fontSize:13,color:'#475569',marginTop:2},date:{fontSize:12,color:'#94a3b8',marginTop:4},add:{position:'absolute',right:20,bottom:24,flexDirection:'row',alignItems:'center',gap:8,backgroundColor:'#2b4594',borderRadius:28,paddingHorizontal:18,paddingVertical:14,elevation:4},addText:{color:'#fff',fontWeight:'800',fontSize:15},overlay:{flex:1,backgroundColor:'rgba(15,23,42,0.45)',justifyContent:'flex-end'},sheet:{backgroundColor:'#fff',borderTopLeftRadius:24,borderTopRightRadius:24,padding:22},detailHeader:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},detailTitle:{fontSize:19,fontWeight:'800',color:'#111827'},packageIcon:{marginTop:16,width:54,height:54,borderRadius:16,backgroundColor:'#fff7ed',alignItems:'center',justifyContent:'center'},itemTitle:{fontSize:20,fontWeight:'800',marginTop:10,color:'#111827'},status:{color:'#b45309',fontWeight:'700',marginTop:3},detailRow:{paddingVertical:10,borderBottomWidth:1,borderColor:'#f1f5f9'},detailLabel:{fontSize:12,color:'#64748b',fontWeight:'700',textTransform:'uppercase'},detailValue:{fontSize:15,color:'#111827',marginTop:2},detailExport:{backgroundColor:'#2b4594',borderRadius:12,padding:14,marginTop:18,flexDirection:'row',justifyContent:'center',alignItems:'center',gap:8},buttonText:{color:'#fff',fontWeight:'800'}});
